USE DATABASE ETL_PROJECT_DB;
USE SCHEMA FINANCIAL;
USE WAREHOUSE ETL_PROJECT_WH;

CREATE OR REPLACE PROCEDURE SP_LOAD_ACCOUNTS()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
  COPY INTO RAW_ACCOUNTS (
    ACC_ID, ACC_NAME, TOTAL_SHARES, AUM,
    CASH_BALANCE, OPEN_DATE, CLOSE_DATE,
    AGE, GENDER, MOBILE_NUMBER, EMAIL,
    ACC_ADDRESS
  )
  FROM @AWS_STAGE
  FILE_FORMAT = CSV_FORMAT
  FORCE = TRUE;

  RETURN 'Accounts loaded successfully';
END;
$$;