CREATE OR REPLACE PROCEDURE SP_LOAD_SHARES()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
  COPY INTO RAW_SHARES (
    SHARE_ID, SHARE_NAME, SECTOR,
    TODAY_PRICE, YESTERDAY_PRICE, PRICE_CHANGE,
    MARKET_CAP, HIGH_52W, LOW_52W,
    LAST_UPDATED
  )
  FROM @GCP_STAGE
  FILE_FORMAT = CSV_FORMAT
  FORCE = TRUE;

  RETURN 'Shares loaded successfully';
END;
$$;