--
-- RAW TABLES (daily, truncated after processing)
--

CREATE OR REPLACE TABLE RAW_ACCOUNTS (
  RAW_ID            NUMBER AUTOINCREMENT PRIMARY KEY,
  ACC_ID            VARCHAR,
  ACC_NAME          VARCHAR,
  TOTAL_SHARES      NUMBER(18,2),
  AUM               NUMBER(18,2),
  CASH_BALANCE      NUMBER(18,2),
  OPEN_DATE         DATE,
  CLOSE_DATE        DATE,
  AGE               NUMBER,
  GENDER            VARCHAR,
  MOBILE_NUMBER     VARCHAR,
  EMAIL             VARCHAR,
  ACC_ADDRESS       VARCHAR,
  SOURCE_TAG        VARCHAR DEFAULT 'AWS',
  LOAD_DATE         DATE DEFAULT CURRENT_DATE,
  LOAD_TIMESTAMP    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * from RAW_ACCOUNTS;

CREATE OR REPLACE TABLE RAW_TRANSACTIONS (
  RAW_ID            NUMBER AUTOINCREMENT PRIMARY KEY,
  ACC_ID            VARCHAR,
  SHARE_ID          VARCHAR,
  TXN_TYPE          VARCHAR,
  TXN_CODE          VARCHAR,
  SHARE_PRICE       NUMBER(18,2),
  QUANTITY          NUMBER(18,2),
  TOTAL_AMOUNT      NUMBER(18,2),
  TXN_DATE          DATE,
  EXCHANGE          VARCHAR,
  SOURCE_TAG        VARCHAR DEFAULT 'AZURE',
  LOAD_DATE         DATE DEFAULT CURRENT_DATE,
  LOAD_TIMESTAMP    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT* from RAW_TRANSACTIONS;

CREATE OR REPLACE TABLE RAW_SHARES (
  RAW_ID            NUMBER AUTOINCREMENT PRIMARY KEY,
  SHARE_ID          VARCHAR,
  SHARE_NAME        VARCHAR,
  SECTOR            VARCHAR,
  TODAY_PRICE       NUMBER(18,2),
  YESTERDAY_PRICE   NUMBER(18,2),
  PRICE_CHANGE      NUMBER(18,2),
  MARKET_CAP        NUMBER(18,2),
  HIGH_52W          NUMBER(18,2),
  LOW_52W           NUMBER(18,2),
  LAST_UPDATED      TIMESTAMP,
  SOURCE_TAG        VARCHAR DEFAULT 'GCP',
  LOAD_DATE         DATE DEFAULT CURRENT_DATE,
  LOAD_TIMESTAMP    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
Select * from RAW_SHARES;

-- 
-- BACKUP TABLES (never deleted)
-- 

CREATE OR REPLACE TABLE BACKUP_ACCOUNTS (
  BACKUP_ID         NUMBER AUTOINCREMENT PRIMARY KEY,
  ACC_ID            VARCHAR,
  ACC_NAME          VARCHAR,
  TOTAL_SHARES      NUMBER(18,2),
  AUM               NUMBER(18,2),
  CASH_BALANCE      NUMBER(18,2),
  OPEN_DATE         DATE,
  CLOSE_DATE        DATE,
  AGE               NUMBER,
  GENDER            VARCHAR,
  MOBILE_NUMBER     VARCHAR,
  EMAIL             VARCHAR,
  ACC_ADDRESS       VARCHAR,
  SOURCE_TAG        VARCHAR DEFAULT 'AWS',
  PROCESSED_DATE    DATE DEFAULT CURRENT_DATE,
  PROCESSED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

select * from BACKUP_ACCOUNTS;

CREATE OR REPLACE TABLE BACKUP_TRANSACTIONS (
  BACKUP_ID         NUMBER AUTOINCREMENT PRIMARY KEY,
  ACC_ID            VARCHAR,
  SHARE_ID          VARCHAR,
  TXN_TYPE          VARCHAR,
  TXN_CODE          VARCHAR,
  SHARE_PRICE       NUMBER(18,2),
  QUANTITY          NUMBER(18,2),
  TOTAL_AMOUNT      NUMBER(18,2),
  TXN_DATE          DATE,
  EXCHANGE          VARCHAR,
  SOURCE_TAG        VARCHAR DEFAULT 'AZURE',
  PROCESSED_DATE    DATE DEFAULT CURRENT_DATE,
  PROCESSED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE BACKUP_SHARES (
  BACKUP_ID         NUMBER AUTOINCREMENT PRIMARY KEY,
  SHARE_ID          VARCHAR,
  SHARE_NAME        VARCHAR,
  SECTOR            VARCHAR,
  TODAY_PRICE       NUMBER(18,2),
  YESTERDAY_PRICE   NUMBER(18,2),
  PRICE_CHANGE      NUMBER(18,2),
  MARKET_CAP        NUMBER(18,2),
  HIGH_52W          NUMBER(18,2),
  LOW_52W           NUMBER(18,2),
  LAST_UPDATED      TIMESTAMP,
  SOURCE_TAG        VARCHAR DEFAULT 'GCP',
  PROCESSED_DATE    DATE DEFAULT CURRENT_DATE,
  PROCESSED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--
-- PRODUCTION TABLES (always latest clean data)
-- 

CREATE OR REPLACE TABLE PROD_ACCOUNTS (
  PROD_ID           NUMBER AUTOINCREMENT PRIMARY KEY,
  ACC_ID            VARCHAR UNIQUE,
  ACC_NAME          VARCHAR,
  TOTAL_SHARES      NUMBER(18,2),
  AUM               NUMBER(18,2),
  CASH_BALANCE      NUMBER(18,2),
  OPEN_DATE         DATE,
  CLOSE_DATE        DATE,
  AGE               NUMBER,
  GENDER            VARCHAR,
  MOBILE_NUMBER     VARCHAR,
  EMAIL             VARCHAR,
  ACC_ADDRESS       VARCHAR,
  SOURCE_TAG        VARCHAR DEFAULT 'AWS',
  LAST_REFRESHED    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE PROD_TRANSACTIONS (
  PROD_ID           NUMBER AUTOINCREMENT PRIMARY KEY,
  ACC_ID            VARCHAR,
  SHARE_ID          VARCHAR,
  TXN_TYPE          VARCHAR,
  TXN_CODE          VARCHAR UNIQUE,
  SHARE_PRICE       NUMBER(18,2),
  QUANTITY          NUMBER(18,2),
  TOTAL_AMOUNT      NUMBER(18,2),
  TXN_DATE          DATE,
  EXCHANGE          VARCHAR,
  SOURCE_TAG        VARCHAR DEFAULT 'AZURE',
  LAST_REFRESHED    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE PROD_SHARES (
  PROD_ID           NUMBER AUTOINCREMENT PRIMARY KEY,
  SHARE_ID          VARCHAR UNIQUE,
  SHARE_NAME        VARCHAR,
  SECTOR            VARCHAR,
  TODAY_PRICE       NUMBER(18,2),
  YESTERDAY_PRICE   NUMBER(18,2),
  PRICE_CHANGE      NUMBER(18,2),
  MARKET_CAP        NUMBER(18,2),
  HIGH_52W          NUMBER(18,2),
  LOW_52W           NUMBER(18,2),
  LAST_UPDATED      TIMESTAMP,
  SOURCE_TAG        VARCHAR DEFAULT 'GCP',
  LAST_REFRESHED    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 
-- COMPANY SUMMARY TABLE
-- 

CREATE OR REPLACE TABLE COMPANY_SUMMARY (
  SUMMARY_ID        NUMBER AUTOINCREMENT PRIMARY KEY,
  TOTAL_ACCOUNTS    NUMBER,
  TOTAL_AUM         NUMBER(18,2),
  TOTAL_CASH        NUMBER(18,2),
  TOTAL_SHARES      NUMBER(18,2),
  TOTAL_TRANSACTIONS NUMBER,
  TOTAL_TXN_AMOUNT  NUMBER(18,2),
  SUMMARY_DATE      DATE DEFAULT CURRENT_DATE,
  CREATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
select * from COMPANY_SUMMARY;