USE DATABASE ETL_PROJECT_DB;
USE SCHEMA FINANCIAL;
USE WAREHOUSE ETL_PROJECT_WH;

-- STORED PROCEDURE 2: PROCESS TRANSACTIONS
CREATE OR REPLACE PROCEDURE SP_PROCESS_TRANSACTIONS()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
  row_count INTEGER;
BEGIN
  IF (SYSTEM$STREAM_HAS_DATA('STREAM_TRANSACTIONS')) THEN

    -- Step 1: Copy RAW to BACKUP
    INSERT INTO BACKUP_TRANSACTIONS (
      ACC_ID, SHARE_ID, TXN_TYPE, TXN_CODE,
      SHARE_PRICE, QUANTITY, TOTAL_AMOUNT,
      TXN_DATE, EXCHANGE, SOURCE_TAG
    )
    SELECT
      ACC_ID, SHARE_ID, TXN_TYPE, TXN_CODE,
      SHARE_PRICE, QUANTITY, TOTAL_AMOUNT,
      TXN_DATE, EXCHANGE, SOURCE_TAG
    FROM STREAM_TRANSACTIONS
    WHERE METADATA$ACTION = 'INSERT';

    -- Step 2: Insert RAW to PROD
    INSERT INTO PROD_TRANSACTIONS (
      ACC_ID, SHARE_ID, TXN_TYPE, TXN_CODE,
      SHARE_PRICE, QUANTITY, TOTAL_AMOUNT,
      TXN_DATE, EXCHANGE, SOURCE_TAG
    )
    SELECT
      ACC_ID, SHARE_ID, TXN_TYPE, TXN_CODE,
      SHARE_PRICE, QUANTITY, TOTAL_AMOUNT,
      TXN_DATE, EXCHANGE, SOURCE_TAG
    FROM RAW_TRANSACTIONS;

    SELECT COUNT(*) INTO :row_count FROM PROD_TRANSACTIONS;
    RETURN 'Transactions processed. PROD count: ' || row_count;
  ELSE
    RETURN 'No new data in STREAM_TRANSACTIONS';
  END IF;
END;
$$;