CREATE OR REPLACE PROCEDURE SP_PROCESS_ACCOUNTS()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
  row_count INTEGER;
BEGIN
  IF (SYSTEM$STREAM_HAS_DATA('STREAM_ACCOUNTS')) THEN

    -- Step 1: Copy RAW to BACKUP
    INSERT INTO BACKUP_ACCOUNTS (
      ACC_ID, ACC_NAME, TOTAL_SHARES, AUM,
      CASH_BALANCE, OPEN_DATE, CLOSE_DATE,
      AGE, GENDER, MOBILE_NUMBER, EMAIL,
      ACC_ADDRESS, SOURCE_TAG
    )
    SELECT
      ACC_ID, ACC_NAME, TOTAL_SHARES, AUM,
      CASH_BALANCE, OPEN_DATE, CLOSE_DATE,
      AGE, GENDER, MOBILE_NUMBER, EMAIL,
      ACC_ADDRESS, SOURCE_TAG
    FROM STREAM_ACCOUNTS
    WHERE METADATA$ACTION = 'INSERT';

    -- Step 2: Insert RAW to PROD
    INSERT INTO PROD_ACCOUNTS (
      ACC_ID, ACC_NAME, TOTAL_SHARES, AUM,
      CASH_BALANCE, OPEN_DATE, CLOSE_DATE,
      AGE, GENDER, MOBILE_NUMBER, EMAIL,
      ACC_ADDRESS, SOURCE_TAG
    )
    SELECT
      ACC_ID, ACC_NAME, TOTAL_SHARES, AUM,
      CASH_BALANCE, OPEN_DATE, CLOSE_DATE,
      AGE, GENDER, MOBILE_NUMBER, EMAIL,
      ACC_ADDRESS, SOURCE_TAG
    FROM RAW_ACCOUNTS;

    SELECT COUNT(*) INTO :row_count FROM PROD_ACCOUNTS;
    RETURN 'Accounts processed. PROD count: ' || row_count;
  ELSE
    RETURN 'No new data in STREAM_ACCOUNTS';
  END IF;
END;
$$;