USE DATABASE ETL_PROJECT_DB;
USE SCHEMA FINANCIAL;
USE WAREHOUSE ETL_PROJECT_WH;

-- STORED PROCEDURE 3: PROCESS SHARES
CREATE OR REPLACE PROCEDURE SP_PROCESS_SHARES()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
  row_count INTEGER;
BEGIN
  IF (SYSTEM$STREAM_HAS_DATA('STREAM_SHARES')) THEN

    INSERT INTO BACKUP_SHARES (
      SHARE_ID, SHARE_NAME, SECTOR,
      TODAY_PRICE, YESTERDAY_PRICE, PRICE_CHANGE,
      MARKET_CAP, HIGH_52W, LOW_52W,
      LAST_UPDATED, SOURCE_TAG
    )
    SELECT
      SHARE_ID, SHARE_NAME, SECTOR,
      TODAY_PRICE, YESTERDAY_PRICE, PRICE_CHANGE,
      MARKET_CAP, HIGH_52W, LOW_52W,
      LAST_UPDATED, SOURCE_TAG
    FROM STREAM_SHARES
    WHERE METADATA$ACTION = 'INSERT';

    INSERT INTO PROD_SHARES (
      SHARE_ID, SHARE_NAME, SECTOR,
      TODAY_PRICE, YESTERDAY_PRICE, PRICE_CHANGE,
      MARKET_CAP, HIGH_52W, LOW_52W,
      LAST_UPDATED, SOURCE_TAG
    )
    SELECT
      SHARE_ID, SHARE_NAME, SECTOR,
      TODAY_PRICE, YESTERDAY_PRICE, PRICE_CHANGE,
      MARKET_CAP, HIGH_52W, LOW_52W,
      LAST_UPDATED, SOURCE_TAG
    FROM RAW_SHARES;

    TRUNCATE TABLE RAW_SHARES;

    SELECT COUNT(*) INTO :row_count FROM PROD_SHARES;
    RETURN 'Shares processed. PROD count: ' || row_count;
  ELSE
    RETURN 'No new data in STREAM_SHARES';
  END IF;
END;
$$;