USE DATABASE ETL_PROJECT_DB;
USE SCHEMA FINANCIAL;
USE WAREHOUSE ETL_PROJECT_WH;

CREATE OR REPLACE PROCEDURE SP_UPDATE_SUMMARY()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
  INSERT INTO COMPANY_SUMMARY (
    TOTAL_ACCOUNTS,
    TOTAL_AUM,
    TOTAL_CASH,
    TOTAL_SHARES,
    TOTAL_TRANSACTIONS,
    TOTAL_TXN_AMOUNT
  )
  SELECT
    COUNT(DISTINCT ACC_ID),
    SUM(AUM),
    SUM(CASH_BALANCE),
    SUM(TOTAL_SHARES),
    (SELECT COUNT(*) FROM PROD_TRANSACTIONS),
    (SELECT SUM(TOTAL_AMOUNT) FROM PROD_TRANSACTIONS)
  FROM PROD_ACCOUNTS;

  RETURN 'Company summary updated successfully';
END;
$$;