USE DATABASE ETL_PROJECT_DB;
USE SCHEMA FINANCIAL;
USE WAREHOUSE ETL_PROJECT_WH;


select * from STREAM_ACCOUNTS;
-- STREAMS
-- Drop and recreate streams


CREATE OR REPLACE STREAM STREAM_ACCOUNTS
  ON TABLE RAW_ACCOUNTS
  APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM STREAM_TRANSACTIONS
  ON TABLE RAW_TRANSACTIONS
  APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM STREAM_SHARES
  ON TABLE RAW_SHARES
  APPEND_ONLY = TRUE;

--- task
-- Run at midnight IST every day
CREATE OR REPLACE TASK TASK_ACCOUNTS
  WAREHOUSE = ETL_PROJECT_WH
  SCHEDULE = 'USING CRON 0 18 * * * UTC'
  WHEN SYSTEM$STREAM_HAS_DATA('STREAM_ACCOUNTS')
AS
  CALL SP_PROCESS_ACCOUNTS();

CREATE OR REPLACE TASK TASK_TRANSACTIONS
  WAREHOUSE = ETL_PROJECT_WH
  SCHEDULE = 'USING CRON 0 18 * * * UTC'
  WHEN SYSTEM$STREAM_HAS_DATA('STREAM_TRANSACTIONS')
AS
  CALL SP_PROCESS_TRANSACTIONS();

CREATE OR REPLACE TASK TASK_SHARES
  WAREHOUSE = ETL_PROJECT_WH
  SCHEDULE = 'USING CRON 0 18 * * * UTC'
  WHEN SYSTEM$STREAM_HAS_DATA('STREAM_SHARES')
AS
  CALL SP_PROCESS_SHARES();

CREATE OR REPLACE TASK TASK_SUMMARY
  WAREHOUSE = ETL_PROJECT_WH
  SCHEDULE = 'USING CRON 0 18 * * * UTC'
AS
  CALL SP_UPDATE_SUMMARY();

-- RESUME ALL
ALTER TASK TASK_ACCOUNTS RESUME;
ALTER TASK TASK_TRANSACTIONS RESUME;
ALTER TASK TASK_SHARES RESUME;
ALTER TASK TASK_SUMMARY RESUME;


