


CREATE OR REPLACE PROCEDURE SP_LOAD_TRANSACTIONS()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
  COPY INTO RAW_TRANSACTIONS (
    ACC_ID, SHARE_ID, TXN_TYPE, TXN_CODE,
    SHARE_PRICE, QUANTITY, TOTAL_AMOUNT,
    TXN_DATE, EXCHANGE
  )
  FROM @AZURE_STAGE
  FILE_FORMAT = CSV_FORMAT
  FORCE = TRUE;

  RETURN 'Transactions loaded successfully';
END;
$$;